### ISSUE TITLE
Nginx upload limit size

### ISSUE THREAD

**Issue by baradhili** [cnvs/canvas#742] opened 2020-05-15 09:27 UTC
Hi,
I have just installed canvas and tried my first post :)..
When I upload an image I'm getting an error "Error during upload  tap to retry"
The image is 1.3MB and I can see it has been uploaded to /storage/app/public/canvas/images

Any idea what I have done wrong?

**Comment by baradhili** [comment] 2020-05-15 10:10
playing around it seems to get upset if the image size is >1MB? (largest I tested that worked was 957kb)

**Comment by austintoddj** [comment] 2020-05-15 18:59
Hm interesting. Are there any logs that give more info on the error?

**Comment by davidgrzyb** [comment] 2020-05-15 23:45
I've run into this before and couldn't figure out why. I remember having to re-export an image to JPEG for it to upload properly because the PNG would upload to 100% and then fail. Unfortunately I can't reproduce this now.

**Comment by baradhili** [comment] 2020-05-16 01:18
ahh.. `2020/05/16 01:17:25 [error] 1365#1365: *6 client intended to send too large body: 1318859 bytes, client: 192.168.10.1, server: www-ticm.local, request: "POST /canvas/api/media/uploads HTTP/1.1", host: "www-ticm.local", referrer: "http://www-ticm.local/canvas/posts/dc9b1b71-cf7b-4a81-bea7-68afd5f9baa7/edit"` now to find out why

**Comment by baradhili** [comment] 2020-05-16 01:25
ok solution seems to be that by default nginx limits uploads to 1M
however its not so simple to override this - https://stackoverflow.com/a/14358928/9708285 is what I have followed which fixed it - maybe something worthwhile for the wiki?

**Comment by austintoddj** [comment] 2020-05-16 14:18
Good find. I'll close this out since it's not a bug with the package, but I'll see if it can fit in somewhere in the readme.

**Closed by austintoddj** 2020-05-16 14:18 UTC
Labels: needs more info
