### ISSUE TITLE
Tag and Topic cant not use Chinese

### ISSUE THREAD

**Issue by maotou316** [cnvs/canvas#791] opened 2020-08-12 06:13 UTC
add tag or add topic can't use chinese
but first character use english is  success
![image](https://user-images.githubusercontent.com/28297458/89981160-fc5eb080-dca5-11ea-96f7-5a3b542145b2.png)
![image](https://user-images.githubusercontent.com/28297458/89981176-0680af00-dca6-11ea-9cd5-b65bb646ad07.png)

**Comment by austintoddj** [comment] 2020-08-12 14:25
This is a duplicate of #612 

Closing this out so the conversation can be kept in one spot, but hopefully will get a fix in for this soon.

**Closed by austintoddj** 2020-08-12 14:25 UTC
Labels: bug
