### ISSUE TITLE
 Search bar for posts on the Admin side

### ISSUE THREAD

**Issue by novocent** [cnvs/canvas#702] opened 2020-04-10 17:38 UTC
Is there any way to search or filter posts on the admin side?  After publishing a dozen or so posts I'm finding that the list is becoming unwieldy.

![Screen Shot 2020-04-10 at 1 34 54 PM](https://user-images.githubusercontent.com/3177296/79010555-366d4980-7b30-11ea-91c2-f9b9f4e9d1ce.jpg)

**Comment by austintoddj** [comment] 2020-04-10 17:49
There used to be a simple post title filter, and there's currently a [pull request](https://github.com/cnvs/canvas/pull/694) for this, but I haven't had the time to look through it or get it refined yet. I'll look at adding this into one of the next releases.

**Comment by austintoddj** [comment] 2020-04-14 19:52
Closing since it's a duplicate of https://github.com/cnvs/canvas/issues/687

**Closed by austintoddj** 2020-04-14 19:52 UTC
Labels: feature
